### ISSUE TITLE
Failed init

### ISSUE THREAD

**Issue by cryptolok** [cappsule/nofear#1]
After `YOLO`installation with root on a physical machine and patch `apply`ing, when trying to launch `nofear`:

>   Error: KVM_CREATE_VM ioctl
>   Warning: Failed init: kvm__init
>  Fatal: Initialisation failed

Exit status 128.

Kernel logs indicate:

> kvm: enabling virtualization on CPUx failed

Whereas host CPU supports VMX and I use KVM regularly.

Any suggestions?

**Comment by cappsule** [comment]
Thanks for the bug report. The error seems to be related to KVM, not NoFear.

I dug through the Linux kernel source code and I assume you get this error because another hypervisor is running. [`hardware_enable()` returns `-EBUSY`](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/x86/kvm/vmx.c?id=c5a6d5f7faad8549bb5ff7e3e5792e33933c5b9f#n3242) if the bit `VMXE` of `CR4` is set. Can you confirm that another hypervisor is running?

**Comment by cryptolok** [comment]
Yep, you're right...
I forgot about another hypervisor...
Runs great by the way.
Nice project and thanks!
