### ISSUE TITLE
Why not use rkt instead of kvmtool?

### ISSUE THREAD

**Issue by NodeGuy** [cappsule/nofear#5]
Great project idea, you're getting me excited!  I plan to start digging in but my first reaction is to ask why not use `rkt` instead of `kvmtool`—does it not solve some of the same problems as your scripts but at a higher level?

**Comment by cappsule** [comment]
I'm no rkt expert but rkt is a container manager which relies on Linux namespaces and cgroups to ensure containers' security. Since an attacker can use a kernel vulnerability to escape from the container, I prefer to rely on hardware virtualization, hence kvmtool.
By the way, did you know that rkt implements an (experimental?) [stage1](https://coreos.com/rkt/docs/latest/running-lkvm-stage1.html) to make use of LKVM (Linux KVM tool, ie. kvmtool) instead of namespaces and cgroups?

Besides, I think that nofear is quite different from containers because it allows any command to be run  transparently in a VM, without any configuration. Containers require a different image to be built for each application.

**Comment by NodeGuy** [comment]
> By the way, did you know that rkt implements an (experimental?) stage1 to make use of LKVM (Linux KVM tool, ie. kvmtool) instead of namespaces and cgroups?

Yes, I learned that from your blog article ("It's worth noting that kvmtool is rkt's hypervisor") which is what made me take a look at `rkt`, thank you.

> Besides, I think that nofear is quite different from containers because it allows any command to be run transparently in a VM, without any configuration. Containers require a different image to be built for each application.

That's a good point.  As I get my mind around this though I think I do want different images for each application.  I found your project after being inspiring by Qubes OS and that's they way they do it.  Another GitHub user, @ypid, wrote up [his opinion](https://github.com/subuser-security/subuser/issues/268#issuecomment-175174254) about this issue after evaluating [Subuser](http://subuser.org/) (different image for each application) vs. [Firejail](https://firejail.wordpress.com/) (no configuration necessary, like NoFear):

> The program is running in its own chroot image which has nothing to do with the main system. (This was the main reason I checkout out Subuser again and is a big plus)
